["protostar.config"]
protostar_version = "0.2.1"

["protostar.project"]
libs_path = "../cairo-pools/"

["protostar.contracts"]
main = [
    "../cairo-pools/contracts/src/Pool.cairo"
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]